import express from 'express';
import roleRoutes from './permissions/roleRoutes';
import moduleRoutes from './modules/moduleRoutes';
import permissionRoutes from './permissions/permissionRoutes';
import userRoutes from './user/userRoutes';
import loginRoutes from './auth/loginRoutes';
import studentRoutes from './student/studentRoutes';
import sessionRoutes from './student/sessionRoutes';
import courseRoutes from './student/courseRoutes';
import semesterRoutes from './student/semesterRoutes';
import sectionRoutes from './student/sectionRoutes';
import employeeRoutes from './employee/employeeRoutes';
import departmentRoutes from './employee/departmentRoutes';
import designationRoutes from './employee/designationRoutes';
import noticeRoutes from './notice/noticeRoutes';
import dashboardRoutes from './dashboard/dashboardRoutes';
import incomeHeadRoutes from './income_expense/incomeHeadRoutes';
import incomeRoutes from './income_expense/incomeRoutes';
import expenseHeadRoutes from './income_expense/expenseHeadRoutes';
import expenseRoutes from './income_expense/expenseRoutes';
import parentDetailsRoutes from './student/parentsDetailsRoutes';
import resultRoutes from './student/resultRoutes';
import payrollRoutes from './employee/payrollRoutes';
import staffAttendanceRoutes from './employee/staffAttendanceRoutes';
import staffLoanRoutes from './employee/staffLoanRoutes';
import installmentRoutes from './employee/installmentRoutes';
import feesTypeRoutes from './fees/feesTypeRoutes';
import feesGroupRoutes from './fees/feesGroupRoutes';
import discountRoutes from './student/discountRoutes';
import feesMasterRoutes from './fees/feesMasterRoutes';
import feesPaymentRoutes from './fees/feesPaymentRoutes';
import communicationRoutes from './communication/sendSmsRoutes';
import fineRoutes from './fees/fineRoutes';
import bankPaymentRoutes from './fees/bankPaymentRoutes';
import leaveTypeRoutes from './leave/leaveTypeRoutes';
import leaveDetailRoutes from './leave/leaveDetailsRoutes';
import leaveRoutes from './leave/leaveRoutes';
import activityRoutes from './activityLog/activityLogRoutes';
import reportRoutes from './report/reportRoutes';

const router = express.Router();

router.use('/roles', roleRoutes);
router.use('/module', moduleRoutes);
router.use('/permission', permissionRoutes);
router.use('/user', userRoutes);
router.use('/auth', loginRoutes);
router.use('/student', studentRoutes);
router.use('/session', sessionRoutes);
router.use('/course', courseRoutes);
router.use('/semester', semesterRoutes);
router.use('/section', sectionRoutes);
router.use('/employee', employeeRoutes);
router.use('/department', departmentRoutes);
router.use('/designation', designationRoutes);
router.use('/notice', noticeRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/income-head', incomeHeadRoutes);
router.use('/income', incomeRoutes);
router.use('/expense-head', expenseHeadRoutes);
router.use('/expense', expenseRoutes);
router.use('/parents-details', parentDetailsRoutes);
router.use('/result', resultRoutes);
router.use('/payroll', payrollRoutes);
router.use('/attendance', staffAttendanceRoutes);
router.use('/staff-loan', staffLoanRoutes);
router.use('/installment', installmentRoutes);
router.use('/fees-type', feesTypeRoutes);
router.use('/fees-group', feesGroupRoutes);
router.use('/discount', discountRoutes);
router.use('/fees-master', feesMasterRoutes);
router.use('/payment', feesPaymentRoutes);
router.use('/communication', communicationRoutes);
router.use('/fine', fineRoutes);
router.use('/bank-payment', bankPaymentRoutes);
router.use('/leave-type', leaveTypeRoutes);
router.use('/leave-detail', leaveDetailRoutes);
router.use('/leave', leaveRoutes);
router.use('/activity-log', activityRoutes);
router.use('/report', reportRoutes);

export default router;
